### ISSUE TITLE
bug:Upper case 

### ISSUE THREAD

**Issue by btxkenshin** [cyanzhong/xTextHandler#10]
HHLogWarn(@"joinChatRequest:%@", jsonObject);

```
joinChatRequest->JOINCHATREQUESt
```

**Comment by cyanzhong** [comment]
What is the version of your Xcode?

It seems like a bug of XcodeKit

**Comment by btxkenshin** [comment]
Version 8.0 (8A218a)

**Comment by cyanzhong** [comment]
You should upgrade Xcode to 8.2, i suggest.
