### ISSUE TITLE
Missing Something?

### ISSUE THREAD

**Issue by justinlevi** [cyanzhong/xTextHandler#3]
Sorry if this is a silly question. I've gone through these steps, but I'm not seeing anything under the Editor Menu. 

* running Xcode 8 
* signed everything with my developer certificate
* build and run the project
* restarted xcode

---

1. Install Xcode 8
2. sudo /usr/libexec/xpccachectl in macOS EI Capitan
3. Sign every targets (app & extensions) using your developer certificate
4. Build & Run
5. Choose Xcode 8 to debug (Or restart Xcode)
6. Select text
7. Open Editor menu to find extensions
8. You can set a shortcut (Key-Binding) for each extension

---

**Comment by cyanzhong** [comment]
did you executed "sudo /usr/libexec/xpccachectl" and restart system ?

**Comment by justinlevi** [comment]
Yes, I restarted Xcode and Restarted OSX. 

Running 10.11.6 (15G1004)

![screen shot 2016-09-19 at 8 12 11 pm](https://cloud.githubusercontent.com/assets/1117989/18653090/8ba0d6f0-7ea5-11e6-8cff-4dc0c8c3644e.jpg)

**Comment by cyanzhong** [comment]
@justinlevi You need open a "Source Code File" (like *.m or *.swift)

Xcode **Source** Editor Extension dynamically display for this kind of files.

**Comment by justinlevi** [comment]
Whoa, super bizarre... after doing all of the above, I wasn't seeing the extension options when editing any source files, so I was reading up on Russ Bishop's blog post about this subject: http://www.russbishop.net/xcode-extensions

I noticed he said you would have two xcode versions running so I decided to try and do a 

( ⌘ + R ) again randomly and I got a modal option to "Choose an app to Run..."

If I then select XCode, I see the menu items although it seems kind of buggy. Is this the correct way to do this? 


![xtextmatcher](https://cloud.githubusercontent.com/assets/1117989/18653615/0930f0fc-7ea9-11e6-826e-88a2b30bc587.gif)

**Comment by cyanzhong** [comment]
maybe a bug of debugger, try build & run app(main) target then restart Xcode to test it.

by the way, upgrade Xcode if you're using a beta version.

**Comment by justinlevi** [comment]
@cyanzhong Thanks so much for responding! I'm running the latest GM release of XCode so I don't think that's the issue. I've restarted XCode a few times too so I don't think that's it either. I'll keep looking into this though as I'm desperate to get this working. 

If XCode had all of the same IDE functionality of something like Sublime, I'd be much much happier :) 

Thanks for posting this as open source as well. Really great reading through your code.
