### ISSUE TITLE
after do as the step, a window show! why?

### ISSUE THREAD

**Issue by Dast1990** [cyanzhong/xTextHandler#6]
按教程一步步操作，结果运行下载的demo后，只是出现了一个名字为window的窗口，打开其他工程，通过editor并没有相关菜单。我的系统是macOS Serria,请问是我操作有问题吗？或者是其他原因？
截图链接如下：https://pan.baidu.com/s/1cDqths

**Comment by cyanzhong** [comment]
我建议先完整的看完 WWDC 的视频，搞清楚 Xcode Source Editor Extension 的运作方式。

然后最重要的一点，一定要记得签名。
