### ISSUE TITLE
After installation, you do not see the menu

### ISSUE THREAD

**Issue by devalios** [cyanzhong/xTextHandler#8]
Why does not appear in the menu editor option? Installed the app in the AppStore. None extension does not appear for some reason.

macOs Sierra 10.12.1
Xcode 8.1

<img width="1680" alt="texthandler" src="https://cloud.githubusercontent.com/assets/2991513/19802779/91e3ffc8-9d05-11e6-844c-df29c7c0f652.png">

**Comment by ofEver** [comment]
+1

**Comment by Dast1990** [comment]
+1

**Comment by AmmarSaadDine** [comment]
+1

**Comment by devalios** [comment]
I found the menu extensions enabled to view it
<img width="852" alt="kepernyofoto 2016-11-04 - 7 44 53 masolat" src="https://cloud.githubusercontent.com/assets/2991513/19996894/28d2f530-a263-11e6-9860-0b0996a3017c.png">

<img width="852" alt="kepernyofoto 2016-11-04 - 7 43 55" src="https://cloud.githubusercontent.com/assets/2991513/19996908/36d3b110-a263-11e6-8e9d-e77b50907a3f.png">

**Comment by cyanzhong** [comment]
@devalios thanks a lot!
