### ISSUE TITLE
No extension in system preferences extensions or in Xcode

### ISSUE THREAD

**Issue by AddictArts** [cyanzhong/xTextHandler#9]
Do you need to reboot?

**Comment by cyanzhong** [comment]
check by following steps:

1. If your macOS is `EI Capitan`, open terminal: sudo /usr/libexec/xpccachectl then reboot
2. Sign every targets (app & extensions) using your developer certificate

**Comment by AddictArts** [comment]
I was using the one in the AppStore, I'll clone and build. Bummer Xcode extensions are this encumbered.

**Comment by AddictArts** [comment]
I did a build and run and still nothing in extensions for Xcode. I also made sure to make the targets signed by me, personal team. Any ideas?

**Comment by AddictArts** [comment]
So, you have to be a paying Apple developer to run this?

**Comment by cyanzhong** [comment]
No, join Apple Developer Program is not required

**Comment by AddictArts** [comment]
I'm out of ideas. I tried and cannot tell if gatekeeper is causing the problem. The app runs and I can debug it, don't need to though as far as I can tell. After it runs I should see the extension in the system preferences right?

**Comment by btxkenshin** [comment]
@AddictArts There must be at least two version of Xcode in your mac, and the xcode worked in commond line as default is not xcod8 . Here is the way to solve your problem:

1. run ```xcode-select --print-path``` to see the default version
2. run ```sudo xcode-select -switch /Applications/Xcode8.app/Contents/Developer``` to change it to the exact version you should.
3. clean the DeviceData & Delete the app(if you also download from the appstore)
4. retry the xTextHandler install

@cyanzhong 目测大多数有问题跑不了这个extension的同学应该都是装了多个xcode且xcode-select设置的不对

**Comment by AddictArts** [comment]
Unfortunately that did not help. Thanks for trying to help. It just does not work for me.
```
/ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
```
I only have one. I went through the steps and I never see the Xcode listing in extensions. I also never see the extensions in Xcode itself. Don't worry about troubleshooting this any further. I have also built this project, run it, and nothing.
